name: Check and build chatger-tui

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  setup:
    name: Setup build env
    runs-on: self-hosted
    outputs:
      cache-key: ${{ steps.setup.outputs.cache-key }}
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Set up Cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
          key: cargo-cache-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-cache-
            cargo-git-
            cargo-index-

  checks:
    name: Check chatger-tui
    needs: setup
    runs-on: self-hosted
    steps:
      - name: Check Rust formatting
        run: |
          nix develop --command cargo fmt --check
      - name: Check Rust linting
        run: |
          nix develop --command cargo clippy --no-deps --frozen

  build:
    name: Builds chatger-tui
    needs: checks
    strategy:
      matrix:
        os: [ self-hosted ]
        target: [x86_64-linux, aarch64-linux, windows]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Build chatger-tui for ${{ matrix.target }}
        run: nix build .#${{ matrix.target }}
     
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: chatgertui-${{ matrix.target }}
          path: |
            ./result/bin/chatgertui
            ./result/bin/chatgertui.exe
            
  release:
    name: Releases chatger-tui
    needs: build
    runs-on: self-hosted
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download x86_64-linux artifact
        uses: actions/download-artifact@v3
        with:
          name: chatgertui-x86_64-linux
          path: ./artifacts/x86_64-linux

      - name: Download aarch64-linux artifact
        uses: actions/download-artifact@v3
        with:
          name: chatgertui-aarch64-linux
          path: ./artifacts/aarch64-linux

      - name: Download windows artifact
        uses: actions/download-artifact@v3
        with:
          name: chatgertui-windows.exe
          path: ./artifacts/windows

      - name: Create GitHub release
        uses: actions/create-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: "Automated release for version ${{ github.ref_name }}"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload x86_64-linux binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          path: ./artifacts/x86_64-linux/chatger-tui
          asset_name: chatger-tui-x86_64-linux
          asset_content_type: application/octet-stream

      - name: Upload aarch64-linux binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          path: ./artifacts/aarch64-linux/chatgertui
          asset_name: chatger-tui-aarch64-linux
          asset_content_type: application/octet-stream

      - name: Upload Windows binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          path: ./artifacts/windows/chatgertui.exe
          asset_name: chatger-tui-windows.exe
          asset_content_type: application/octet-stream
